language: python

sudo: false

cache:
  directories:
    - $HOME/miniconda

# Removing the directory will remove the env but leave the cached packages
# at $HOME/miniconda/pkgs. That is a win-win because when re-creating the
# env we will download only the new packages.
before_cache:
  - rm -rf $HOME/miniconda/envs/TEST

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=default
  - python: 3.5
    env: TEST_TARGET=default
  - python: 3.6
    env: TEST_TARGET=coding_standards

before_install:
  - |
    echo ""
    if [ ! -f $HOME/miniconda/bin/conda ] ; then
      echo "Fresh miniconda installation."
      wget http://bit.ly/miniconda -O miniconda.sh
      rm -rf $HOME/miniconda
      bash miniconda.sh -b -p $HOME/miniconda
    fi

  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update conda
  - conda config --add channels conda-forge --force
  - conda create -n TEST python=$TRAVIS_PYTHON_VERSION --file requirements.txt --file requirements-dev.txt
  - source activate TEST

install:
  - python setup.py sdist && version=$(python setup.py --version) && pushd dist  && pip install odvc-${version}.tar.gz && popd

script:
  - if [[ $TEST_TARGET == 'default' ]]; then
      py.test -s -rxs -v test;
    fi

  - if [[ $TEST_TARGET == 'coding_standards' ]]; then
      flake8 odvc --max-line-length=100 --exclude _version.py ;
      flake8 test --max-line-length=100 ;
    fi

